### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by Kai-web** [zhihuifanqiechaodan/miniprogram-template#2]
![image](https://user-images.githubusercontent.com/59676989/201476669-459b4a56-2fb7-4774-97d6-254e6e7248fe.png)

**Comment by zhihuifanqiechaodan** [comment]
> ![图片](https://user-images.githubusercontent.com/59676989/201476669-459b4a56-2fb7-4774-97d6-254e6e7248fe.png)

刚看到，我这边使用node14版本，通过yarn安装没有出现上述问题，请问现在问题还在吗。

**Comment by Kai-web** [comment]
我换了 16.17.1 版本也报了这个
![image](https://user-images.githubusercontent.com/59676989/202152623-21645874-45cd-4891-885f-511516eda908.png)

**Comment by zhihuifanqiechaodan** [comment]
> 我换了 16.17.1 版本也报了这个 ![image](https://user-images.githubusercontent.com/59676989/202152623-21645874-45cd-4891-885f-511516eda908.png)

删除版本锁定文件，然后重新安装依赖试试
